apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ .Chart.Name }}
  minReplicas: {{ .Values.autoscaler.minCount }}
  maxReplicas: {{ .Values.autoscaler.maxCount }}
{{ toYaml .Values.autoscaler.targets | indent 2 }}
