apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
{{ if eq .Values.service.type "ClusterIP" }}
  clusterIP: {{ .Values.service.clusterIP | default "None" | quote }}
{{ end }}
  ports:
  - name: grpc
    protocol: TCP
    port: {{ .Values.service.grpcPort }}
    targetPort: {{ .Values.service.grpcPort }}
  - name: proxy
    protocol: TCP
    port: {{ .Values.service.proxyPort }}
    targetPort: {{ .Values.service.proxyPort }}
  selector:
    app: {{ .Chart.Name }}
