replicasCount: 1
maxUnavailableCount: 0

image:
  repository: registry.videocoin.net/cloud/validator
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: 
  - name: regcred

serviceAccount:
  name: default

config:
  THRESHOLD: "10"
  EMITTER_RPC_ADDR: "emitter.console.svc.cluster.local:5003"

service:
  ports:
    grpc: 5020

autoscaler:
  minCount: 1
  maxCount: 5
  targets:
    targetCPUUtilizationPercentage: 70

resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 50m
    memory: 32Mi

annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "console-validator"
  vault.hashicorp.com/agent-inject-secret-common: "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/console/common/config"
  vault.hashicorp.com/agent-inject-secret-config: "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/console/validator/config"
  vault.hashicorp.com/agent-inject-template-common: |
    {{ with secret "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/console/common/config" }}{{ range $k, $v := .Data }}
    export {{ $k }}="{{ $v }}"
    {{ end }}{{ end }}
  vault.hashicorp.com/agent-inject-template-config: |
    {{ with secret "dev-videocoin-net/github-repo/dev-apps-videocoin-net/charts/console/validator/config" }}{{ range $k, $v := .Data }}
    export {{ $k }}="{{ $v }}"
    {{ end }}{{ end }}
